In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('./extracted/energy_iter5.csv')
df

,Date,DayPeakGen(MW),EveningPeakGen(MW),MaxDemand(MW),MaxGeneration(MW),Temperature,Year,Month,Season,IsHoliday
0,2024-12-31,14543,14949,10600,14949,18.7,2024,12,Winter,No
1,2024-12-31,10596,11883,10100,11883,18.7,2024,12,Winter,No
2,2024-12-30,13760,15475,10800,15475,21.8,2024,12,Winter,No
3,2024-12-29,14372,14729,10800,14729,21.2,2024,12,Winter,No
4,2024-12-28,14138,14492,9850,14492,21.2,2024,12,Winter,No
...,...,...,...,...,...,...,...,...,...,...
1652,2020-06-06,12613,15053,10800,15053,28.8,2020,6,Monsoon,No
1653,2020-06-05,12511,15065,9000,15065,28.3,2020,6,Monsoon,Yes
1654,2020-06-04,12390,15053,11000,15053,27.6,2020,6,Monsoon,No
1655,2020-06-03,12258,14747,11000,14747,28.9,2020,6,Monsoon,No
1656,2020-06-02,11700,14765,11000,14765,29.5,2020,6,Monsoon,No

In [3]:
df.rename(columns={'EveningPeakGen(MW)': 'EvePeakGen(MW)', 'MaxDemand(MW)': 'MaxDem(MW)', 'MaxGeneration(MW)': 'MaxGen(MW)', 'Temperature': 'Temp(C)'}, inplace=True)
df

,Date,DayPeakGen(MW),EvePeakGen(MW),MaxDem(MW),MaxGen(MW),Temp(C),Year,Month,Season,IsHoliday
0,2024-12-31,14543,14949,10600,14949,18.7,2024,12,Winter,No
1,2024-12-31,10596,11883,10100,11883,18.7,2024,12,Winter,No
2,2024-12-30,13760,15475,10800,15475,21.8,2024,12,Winter,No
3,2024-12-29,14372,14729,10800,14729,21.2,2024,12,Winter,No
4,2024-12-28,14138,14492,9850,14492,21.2,2024,12,Winter,No
...,...,...,...,...,...,...,...,...,...,...
1652,2020-06-06,12613,15053,10800,15053,28.8,2020,6,Monsoon,No
1653,2020-06-05,12511,15065,9000,15065,28.3,2020,6,Monsoon,Yes
1654,2020-06-04,12390,15053,11000,15053,27.6,2020,6,Monsoon,No
1655,2020-06-03,12258,14747,11000,14747,28.9,2020,6,Monsoon,No
1656,2020-06-02,11700,14765,11000,14765,29.5,2020,6,Monsoon,No

In [4]:
df.to_csv('./extracted/energy_iter6.csv', index=False)